# Generated by Django 6.0.2 on 2026-02-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(max_length=50, unique=True, verbose_name='Interaction ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('assigned_by', models.CharField(default='AI Agent', max_length=100)),
                ('progress', models.CharField(choices=[('confirmed', 'Confirmed'), ('need_staff', 'Need Staff'), ('need_attention', 'Need Human Attention'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('booking_type', models.CharField(choices=[('new', 'New'), ('urgent', 'Urgent'), ('existing', 'Existing')], default='new', max_length=50)),
                ('booking_info', models.CharField(choices=[('confirmed', 'Confirmed'), ('decline', 'Decline'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_call_summary', models.TextField(blank=True, null=True)),
                ('rezgo_raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
