# Generated by Django 6.0.2 on 2026-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezgoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('rezgo_uid', models.CharField(max_length=50)),
            ],
        ),
    ]
