# Generated by Django 5.2.11 on 2026-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinge', '0002_rezgolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('venue_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookinginquiry',
            options={},
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='group_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
