# Generated by Django 5.2.11 on 2026-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinge', '0003_confirmedbooking_venue_alter_bookinginquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='confirmedbooking',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmedbooking',
            name='status',
            field=models.CharField(default='Confirmed', max_length=50),
        ),
        migrations.AddField(
            model_name='confirmedbooking',
            name='time',
            field=models.CharField(default='12.00 PM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='contact_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='priority',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
