# Generated by Django 5.2.11 on 2026-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinge', '0004_confirmedbooking_email_confirmedbooking_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezgolocation',
            name='city_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rezgolocation',
            name='rezgo_uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
